# Generated by Django 4.0.6 on 2022-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='special',
            field=models.CharField(default='#', max_length=1),
        ),
    ]
