# Generated by Django 4.0.5 on 2022-07-04 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_plug',
            field=models.URLField(default='https://linktr.ee/ndasilva', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
