# Generated by Django 4.0.5 on 2022-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_slug_alter_post_summary_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default='blog', max_length=255),
        ),
    ]
