# Generated by Django 4.0.5 on 2022-07-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default='Tag description.', max_length=255),
        ),
    ]
