# Generated by Django 4.0.5 on 2022-07-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='special',
            field=models.CharField(default='#', max_length=2),
        ),
    ]
