# Generated by Django 4.0.5 on 2022-07-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
