# Generated by Django 4.0.6 on 2022-07-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_email_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_is_verified',
        ),
    ]
