# Generated by Django 4.0.5 on 2022-07-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auditentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditentry',
            options={'verbose_name': 'Audit Entry', 'verbose_name_plural': 'Audit Entries'},
        ),
    ]
