# Generated by Django 4.0.5 on 2022-07-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auditentry_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditentry',
            old_name='timestamp',
            new_name='time',
        ),
    ]
