# Generated by Django 4.0.6 on 2022-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='original_email',
            field=models.EmailField(default='', max_length=254, verbose_name='original email'),
        ),
    ]
