# Generated by Django 4.0.6 on 2022-08-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OTP secret'),
        ),
    ]
