# Generated by Django 4.0.5 on 2022-07-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comment_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
