# Generated by Django 4.0.6 on 2022-08-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_options_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
