# Generated by Django 4.0.6 on 2022-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_tag_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
