# Generated by Django 4.0.5 on 2022-07-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_auditentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
