# Generated by Django 4.0.5 on 2022-07-21 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_previous_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
